function __do_the_thing() {
  echo "Enabling btrfs-scrub k3s sshd"
  systemctl enable --now \
    btrfs-scrub@mnt-rootfs.timer \
    btrfs-scrub@mnt-lucastrunk.timer \
    k3s.service \
    sshd.service

  echo "Setting root password"
  usermod -p '$6$rounds=1000000$7iaxvgAskJvdGQ5V$2icv5tJgTUjnJgQxL0pabzCX7hXUOdeCvLShWeoQ9zkQN1FIlQMYqUIa6a.62HCKYhQWvy5spt8MX/aj6EDwx/' root
}

post_install() {
  __do_the_thing
}

post_upgrade() {
  __do_the_thing
}
