function __do_the_thing() {
  echo "Enabling networkd resolved timesyncd btrfs-scrub smartd paccache reflector"
  systemctl enable --now \
    systemd-networkd.service \
    systemd-resolved.service \
    systemd-timesyncd.service \
    smartd.service \
    paccache.timer \
    reflector.timer

  echo "Using networkd resolv.conf stub"
  ln -sf ../run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
}

post_install() {
  __do_the_thing
}

post_upgrade() {
  __do_the_thing
}
